version: 1.0.{build}
init:
- choco install redis
- redis-server.exe
before_build:
- nuget restore
- packages\Redis-32.2.6.12.1\tools\redis-server.exe packages\Redis-32.2.6.12.1\tools\redis.conf
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal